// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDadRpBBnQF76mmsBRKkjWTOozKYR29UvA',
    appId: '1:401619007074:web:b6bbb8edfa850fda81833b',
    messagingSenderId: '401619007074',
    projectId: 'steamchatcloneapp',
    authDomain: 'steamchatcloneapp.firebaseapp.com',
    storageBucket: 'steamchatcloneapp.appspot.com',
    measurementId: 'G-4K96KEJVTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYM0thbAogXJaUN-Cyc9-VSQuV2hPAtXI',
    appId: '1:401619007074:android:d640ed0daf7502bf81833b',
    messagingSenderId: '401619007074',
    projectId: 'steamchatcloneapp',
    storageBucket: 'steamchatcloneapp.appspot.com',
  );

}